
# Site settings
title: Muricture

description: >-
  캐릭터들의 집합소 Muricture 페이지에 오신 것을 환영합니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://muricture.co.kr/"
twitter_username: ""

# MyData
owner:
  email: tjtjdwh5321@gmail.com
  name : Seongjo seo
  github_username:  seongjo-seo

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag